import { CamoPreset } from '../types/game';

export const CAMO_PRESETS: CamoPreset[] = [
  {
    id: 'blank_white',
    name: 'Blank Plaster',
    nameVi: 'Thạch Cao Trắng',
    color: '#f8fafc',
    pattern: 'solid',
    roughness: 0.85,
    metalness: 0.05,
    recommendedPose: 'standing',
    description: 'Trạng thái ban đầu. Tiệp với các mảng tường trưng bày màu trắng sữa.',
  },
  {
    id: 'terracotta_brick',
    name: 'Ancient Brick',
    nameVi: 'Tường Gạch Cổ',
    color: '#b84a39',
    pattern: 'brick',
    roughness: 0.9,
    metalness: 0.05,
    recommendedPose: 'wall_hug',
    description: 'Ngụy trang tuyệt đối trước bức tường gạch đỏ cổ khu tranh Phục Hưng.',
  },
  {
    id: 'botanical_ivy',
    name: 'Botanical Foliage',
    nameVi: 'Lá Cây Thảo Mộc',
    color: '#2d6a4f',
    pattern: 'foliage',
    roughness: 0.7,
    metalness: 0.1,
    recommendedPose: 'crouch_bush',
    description: 'Hòa mình vào bức tường rêu xanh và chậu cây nhiệt đới tại Nhà Kính.',
  },
  {
    id: 'white_marble',
    name: 'Classical Marble',
    nameVi: 'Cẩm Thạch Hy Lạp',
    color: '#e2e8f0',
    pattern: 'marble',
    roughness: 0.35,
    metalness: 0.15,
    recommendedPose: 'statue_classical',
    description: 'Biến thành pho tượng cẩm thạch trắng đứng cạnh các cột trụ và bệ trưng bày.',
  },
  {
    id: 'gilded_gold',
    name: 'Gilded Bronze',
    nameVi: 'Tượng Đồng Mạ Vàng',
    color: '#d97706',
    pattern: 'gold',
    roughness: 0.25,
    metalness: 0.85,
    recommendedPose: 'thinker',
    description: 'Bề mặt kim loại dát vàng óng ánh trên bệ tượng Hoàng gia.',
  },
  {
    id: 'pop_art_mural',
    name: 'Pop Art Mural',
    nameVi: 'Tranh Trừu Tượng Pop-Art',
    color: '#ef4444',
    pattern: 'popart',
    roughness: 0.6,
    metalness: 0.1,
    recommendedPose: 'wall_hug',
    description: 'Hòa tan vào bức bích họa khối màu Mondrian tại Phòng Triển Lãm Hiện Đại.',
  },
  {
    id: 'mahogany_wood',
    name: 'Mahogany Bookshelf',
    nameVi: 'Gỗ Gụ Thư Viện',
    color: '#451a03',
    pattern: 'wood',
    roughness: 0.75,
    metalness: 0.1,
    recommendedPose: 'standing',
    description: 'Ẩn mình trước kệ sách gỗ cổ điển và các vách ốp lưu trữ tài liệu.',
  },
  {
    id: 'royal_damask',
    name: 'Royal Damask',
    nameVi: 'Gấm Lụa Cung Điện',
    color: '#7f1d1d',
    pattern: 'damask',
    roughness: 0.8,
    metalness: 0.2,
    recommendedPose: 'wall_hug',
    description: 'Họa tiết gấm nhung quý phái trên mảng tường trưng bày đồ cổ.',
  },
  {
    id: 'slate_stone',
    name: 'Dark Slate',
    nameVi: 'Đá Phiến Tối Màu',
    color: '#334155',
    pattern: 'slate',
    roughness: 0.85,
    metalness: 0.2,
    recommendedPose: 'standing',
    description: 'Màu xám than hòa nhập với bệ đỡ hiện đại và khung tường kim loại.',
  },
];
